Create Shooter Subsystem
WolfpackRobotics3859/2024-Robot-Code pull request #11
Opened 2024-01-12 02:05 UTC by coolinm

2024-01-12 03:52 UTC, jasonsoohoo commented on src/main/java/frc/robot/RobotContainer.java
> +  public Drivetrain getDriveSub()
need public Shooter getShooter()

2024-01-12 03:53 UTC, jasonsoohoo commented on src/main/java/frc/robot/RobotContainer.java
> +    primaryController.a().onTrue(new SeedFieldRelative(m_Drivetrain));
get this out of here

2024-01-12 03:54 UTC, jasonsoohoo commented on src/main/java/frc/robot/RobotContainer.java
> +
move constructor here

2024-01-12 03:59 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/shooter/SetShooterMotor1Percent.java
> +    m_Shooter.setShooterMotor1Percent(m_Percent);
this.m_Percent

2024-01-12 03:59 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/shooter/SetShooterMotor1Velocity.java
> +     m_Shooter.setMotor1Velocity(m_Velocity);
this

2024-01-12 04:00 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/shooter/SetShooterMotor2Percent.java
> +    m_Shooter.setShooterMotor2Percent(m_Percent);
this

2024-01-12 04:00 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/shooter/SetShooterMotor2Velocity.java
> +    m_Shooter.setMotor2Velocity(m_Velocity);
this

2024-01-12 04:00 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/shooter/SetWristMotorPercent.java
> +    m_Shooter.setWristPercent(m_Percent);
this

2024-01-12 04:00 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/shooter/SetWristMotorPosition.java
> +    m_Shooter.setWristPos(m_Position);
this

2024-01-12 04:01 UTC, jasonsoohoo commented on src/main/java/frc/robot/constants/shooter/ShooterConstants.java
> +    public static final Slot0Configs SHOOTER_GAINS = new Slot0Configs()
add another gains

2024-01-12 04:02 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    m_ShooterMotor2.getConfigurator().apply(ShooterConstants.SHOOTER_GAINS);
apply after you create it

2024-01-13 21:18 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    switch (motor){
bad opening bracker

2024-01-13 21:18 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    MotionMagicVelocityVoltage request = new MotionMagicVelocityVoltage(velocity, 40, false, 0, 0, false, false, false);
make this 40 a constant

2024-01-13 21:20 UTC, jasonsoohoo requested changes
needs changes

2024-01-13 22:21 UTC, jasonsoohoo approved these changes

2024-01-13 22:38 UTC, cjahner1 approved these changes

2024-01-13 22:38 UTC, merged