3 create intake subsystem
WolfpackRobotics3859/2024-Robot-Code pull request #13
Opened 2024-01-13 22:39 UTC by sconstantine08

2024-01-13 22:54 UTC, cjahner1 approved these changes, later dismissed

2024-01-14 22:11 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/intake/RunIntakeCommand.java
> +public class RunIntakeCommand extends Command {
fix brackets

2024-01-14 22:11 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/intake/RunIntakeCommand.java
> +public class RunIntakeCommand extends Command {
in the whole file

2024-01-14 22:12 UTC, jasonsoohoo commented on src/main/java/frc/robot/constants/intake/IntakeConstants.java
> +    public static final int kTimeoutMs = 10;
kTimeoutMs needs to follow our normal constant standards

2024-01-14 22:15 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    intakeMotor.getConfigurator().apply(IntakeConstants.INTAKE_GAINS);
this.m_IntakeMotor.getConfigurator().....

2024-01-14 22:16 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  private TalonFX intakeMotor = new TalonFX(17);
Talon IDs need to be a constant in the hardware file. Also this needs to be m_IntakeMotor

2024-01-14 22:17 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  public void setIntakePosition(double position)
This method says setIntakePosition but uses motion magic velocity. Why?

2024-01-14 22:18 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/intake/RunIntakeCommand.java
> +        m_intakeSubsystem.setIntakePosition(this.m_velocity);
Why are we passing a velocity into a position method?

2024-01-14 22:21 UTC, jasonsoohoo requested changes
This implementation only has one motor when the intake needs an arm motor and a rolling motor. Also for some reason the method created passes a velocity and acts as a velocity control loop when we don't need it. We need a position loop for the arm and an open duty cycle for the rollers. I also don't know why the method is named setPosition, but then implements a velocity.

2024-01-17 06:01 UTC, jasonsoohoo commented on src/main/java/frc/robot/RobotContainer.java
> +      m_primaryController.b().whileTrue(new RunIntakeCommand(m_Intake, 0.3));
Remove these controller binds. While these are good for testing, they shouldn't be added to our develop branch.

2024-01-17 06:02 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/intake/RunIntakeCommand.java
> +
why extra indent and whitespace. We need to be reading through our code and looking for formatting errors before requesting reviews.

2024-01-17 06:02 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/intake/RunIntakeCommand.java
> +  {
// Intentionally Empty

2024-01-17 06:03 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/intake/RunIntakeCommand.java
> +
//Intentionally Empty

2024-01-17 06:05 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/intake/RunIntakeCommand.java
This file needs to be named better. First off we don't put Command inside the name of our files because it is redundant. I also can't tell what this command is doing at a glance. Does this actuate the arm or does it just roll the rollers? If this is for the rollers then you need something that will stop the rollers. You call this command but you don't have another command that stops the rollers from spinning. Since this was skipped over I feel like we haven't done enough testing, so we need to be more thorough next time.

2024-01-17 06:07 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/intake/RunIntakeCommand.java
> +    addRequirements(intake);
You have several commands here the require the intake. If you attempt to run multiple commands, such as adjusting the wrist angle and shoot at the same time they will collide and one will interrupt the other. For the intake, the subsystems shouldn't be required in any of the commands as they will need to run concurrently.

2024-01-17 06:08 UTC, jasonsoohoo commented on src/main/java/frc/robot/constants/Hardware.java
> +    public static final int INTAKE_MOTOR_ID = 12;
This motor should be named intake rollers or something instead of just intake

2024-01-17 06:08 UTC, jasonsoohoo commented on src/main/java/frc/robot/constants/intake/IntakeConstants.java
> +    public static final Slot0Configs INTAKE_GAINS = new Slot0Configs()
Needs to be renamed to rollers.

2024-01-17 06:09 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  private TalonFX m_IntakeMotor = new TalonFX(Hardware.INTAKE_MOTOR_ID);
RollerMotor or something

2024-01-17 06:09 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +
extra whitespace?

2024-01-17 06:10 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    this.m_WristMotor.getConfigurator().apply(IntakeConstants.MOTION_MAGIC_CONFIGS);
rename this constant to WRIST_MOTOR_MOTION_MAGIC_CONFIGS

2024-01-17 06:10 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  @Override
periodic loop should be placed at the end of the file.

2024-01-17 06:12 UTC, jasonsoohoo requested changes
Intake still needs adjustments. By leaving whitespace errors it makes me think that you're not reading through your code fully before requesting review. This may not be the case, but just avoid mistakes like these so we have more confidence during code review. Also, the biggest issue right now is the fact that I can tell by looking at the code that interrupts would definitely occur, so it does appear this code hasn't fully been tested.

2024-01-18 02:22 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  public void setIntakePercent(double percent)
Rename this function to better reflect what it is setting.

2024-01-18 02:22 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/intake/SetIntakeWristPosition.java
> +    // Intentionally Emptya
Typo

2024-01-18 02:23 UTC, jasonsoohoo requested changes
One more change.

2024-01-18 03:26 UTC, Ferris-Bueller7 submitted a review, later dismissed

2024-01-22 22:57 UTC, jasonsoohoo approved these changes

2024-01-23 02:14 UTC, Ferris-Bueller7 approved these changes

2024-01-23 02:31 UTC, merged