19: Add Feeder motor to Shooter Subsystem
WolfpackRobotics3859/2024-Robot-Code pull request #21
Opened 2024-01-17 02:54 UTC by coolinm

Feeder motor + feeder commands added

Tested and working in shop

2024-01-17 06:20 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/shooter/SetFeederMotorPercent.java
> +   * @brief Applies a percent of the available voltage to shooter motor 1.
You haven't updated your documentation.

2024-01-17 06:21 UTC, jasonsoohoo commented on src/main/java/frc/robot/commands/shooter/SetFeederMotorVelocity.java
> +   * @brief Runs motor number 1 at a given velocity.
Update your documentation

2024-01-17 06:22 UTC, jasonsoohoo requested changes
Requires changes.

2024-01-17 08:20 UTC, coolinm commented
Changes made.

2024-01-18 02:17 UTC, jasonsoohoo approved these changes
Code is approved. Please test before merging.

2024-01-18 03:09 UTC, Ferris-Bueller7 approved these changes

2024-01-18 03:13 UTC, merged