5: Implement PathPlanner
WolfpackRobotics3859/2024-Robot-Code pull request #24
Opened 2024-01-22 23:53 UTC by cjahner1

Add automatic path following to the robot to enable it to navigate to known positions on the field

2024-01-23 20:44 UTC, jasonsoohoo commented on src/main/java/frc/robot/RobotContainer.java
> +      m_primaryController.b().whileTrue(new PathPlannerAuto("Amp Auto"));
Leave binds outside of the main project until we decide them

2024-01-23 20:45 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    for (var moduleLocation : m_moduleLocations) {
brackets

2024-01-23 20:46 UTC, jasonsoohoo commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        return m_kinematics.toChassisSpeeds(getState().ModuleStates);
extra tabs?

2024-01-23 20:46 UTC, jasonsoohoo requested changes
Needs changes

2024-01-23 20:47 UTC, jasonsoohoo commented
Your branch hasn't updated to the latest develop.

2024-01-24 02:59 UTC, cjahner1 commented
Changes made and tested

2024-01-25 00:56 UTC, jasonsoohoo commented
Branch is still not updated, conflicts exist

2024-02-26 20:19 UTC, jasonsoohoo commented
Remove existing auto. Don't implement any autos until we know for sure we are going to use them. It's ok to test, but we should only add paths that are competition ready. Please update constants to reflect the current robot. Update driver base characteristics, update camera locations.

2024-02-26 20:19 UTC, jasonsoohoo requested changes
Please update project

2024-03-17 06:10 UTC, closed without merging